### ISSUE TITLE
Considered packaging as a framework?

### ISSUE THREAD

**Issue by afragen** [collizo4sky/persist-dismissible-admin-notices#1]
This would be great as a drop-in to a `vendor` directory and a simple `require_once()` rather than as a plugin.

Any thoughts to creating a branch for a drop-in framework?

**Comment by w3guy** [comment]
Nice idea. Pull request is welcome if you can do this. Otherwise i will get it done as soon as i have the time.

Update: am taking this up. should be ready before tomorrow.

**Comment by w3guy** [comment]
Done. https://packagist.org/packages/collizo4sky/persist-admin-notices-dismissal
