### ISSUE TITLE
optional: store in setting?

### ISSUE THREAD

**Issue by futtta** [collizo4sky/persist-dismissible-admin-notices#17]
follow-up to https://github.com/collizo4sky/persist-admin-notices-dismissal/issues/16; wouldn't it make sense to allow the dismissal to be stored in a setting iso a transient? :-)

**Comment by afragen** [comment]
It would solve some issues with object caching but also will leave entries to clutter up your options table. As a library there is no uninstall.

**Comment by barisunver** [comment]
The plugin (which uses this lib) should have the responsibility to include it in its uninstall.php tough, right?

**Comment by afragen** [comment]
@collizo4sky I can create a PR to save to the options table. I have code already for this. 

What do you think?

**Comment by w3guy** [comment]
@afragen would be a great idea. I think initially it was saving to an option table when I created.

Go for it.

**Comment by afragen** [comment]
@barisunver ideally yes but we know that’s not likely to happen.  It’s not likely to be many entries. 

@collizo4sky will do. I just need to get off a plane first 😉

**Comment by w3guy** [comment]
@barisunver it will be just a row in the option table. What could possibly go wrong with not removing it?

**Comment by barisunver** [comment]
> @barisunver it will be just a row in the option table. What could possibly go wrong with not removing it?

I wouldn't worry about that row at all, but recommending the plugin/theme dev to make it removable is always a better practice.

**Comment by afragen** [comment]
I have the code to remove it too. I’ll put those instructions in the README.

**Comment by futtta** [comment]
great, me happy! :-)

**Comment by afragen** [comment]
Anyone care to test before I submit a PR? 
https://github.com/afragen/persist-admin-notices-dismissal/tree/set-option

**Comment by futtta** [comment]
I will today/ tomorrow if time permits :)

**Comment by futtta** [comment]
Afraid I have not had time and I'm leaving on holiday soon, so don't let me
hold the PR/ merge back guys! ;-)
