### ISSUE TITLE
cleanup at uninstall issue

### ISSUE THREAD

**Issue by futtta** [collizo4sky/persist-dismissible-admin-notices#21]
Great to have the notice dismissal status being strored in options iso transients (asked some people to test for whom transients did not work) and nice you thought of cleanup code to remove PAnD-options, but ... assuming a use case where 2 or more plugins are installed that use PAnD, this approach deletes the PAnD-options of all plugins, not only of the one being uninstalled?

So what if we save the option as
```php
$cache_key = 'pand-' .md5(<calling plugin slug>) . '-' . md5( $id );
```
And delete only the pand-options for the plugin being uninstalled.

Question is if we can auto-populate <calling plugin slug> or if we would need that to be passed as an option (which is ... tedious)?

frank

**Comment by afragen** [comment]
Yes, you have identified a potential issue. Unfortunately trying to individually remove the options is much more difficult. The only drawback is that the user will see a notice one more time that they must dismiss.

**Comment by afragen** [comment]
We can only hope that everyone using PAnD is cleaning up after themselves. But they likely aren’t. Think of this as a service to everyone else using PAnD with a minimal cost. 😉

**Comment by futtta** [comment]
hmmm ... I would prefer not getting complaints of users seeing my notice(s) because someone else deleted all PAnD options ;-)

Maybe we could we use something like

`debug_backtrace(2,1)[0]['file']
`
which automagically provides us with calling plugin's filename including path (did some tests and seems to work), from which we could extract the slug and then indeed add this to $cache_key as

`$cache_key = 'pand-' .md5(<calling plugin slug>) . '-' . md5( $id );
`
and then only delete 

`%pand-' .md5(<this plugin slug>) . '-%'
`
from the DB?

**Comment by afragen** [comment]
Personally I think the added complexity outweighs the half second of user interaction.

I'm happy to evaluate a PR and see what @collizo4sky has to say.

**Comment by w3guy** [comment]
It’s just one row in option table. I will prefer we do not recommend deleting the option table after unistall.

**Comment by futtta** [comment]
-> "complexity"; agreed. I'm somewhat wary of using `debug_backtrace`, no idea if is can/ should be used like this in a production-setting
-> "outweighs half second user interaction"; problem is we're impacting other plugin's notices, so we're affecting user interactions of other plugins.
-> "not recommending deleting from the option table" indeed is a possibility as well, but not wild about that either to be honest

**Comment by w3guy** [comment]
@afragen shall we now remove the uninstall section from readme?

**Comment by afragen** [comment]
@collizo4sky perhaps a warning about the potential interaction with others in addition to the uninstall section? I have no problem with removing the uninstall section. I added it to be complete.

**Comment by afragen** [comment]
@futtta I don’t believe you can actually pass anything to the `uninstall.php` file as the plugin would be deactivated and it runs on delete.

**Comment by w3guy** [comment]
I am in favor of removing it altogether with a warning not to remove it on uninstall for the sake of other plugins using it.

Fine with everyone?

**Comment by afragen** [comment]
If we don't mention how to remove it, do we need the notice about removing it?

**Comment by w3guy** [comment]
Just to warn those that may have the intention of doing it.

**Comment by afragen** [comment]
@collizo4sky would you like me to submit the PR?

**Comment by w3guy** [comment]
Yes please 🙏🏻

**Comment by afragen** [comment]
Already done. #22

**Comment by w3guy** [comment]
Merged.
