### ISSUE TITLE
Cleanup .gitattributes and .gitignore

### ISSUE THREAD

**Issue by afragen** [collizo4sky/persist-dismissible-admin-notices#23]
Just creating a reminder to myself to cleanup these files.

**Comment by afragen** [comment]
This one will need a release and bump. I didn't change the version number in any of the files. We can put the version number in the composer.json if you want.

**Comment by w3guy** [comment]
Oh no. I already made a release.

**Comment by afragen** [comment]
Next time. 😉

**Comment by w3guy** [comment]
Fixed 😊
