### ISSUE TITLE
WooCommerce WPCS

### ISSUE THREAD

**Issue by Surbma** [collizo4sky/persist-dismissible-admin-notices#40]
The WooCommerce CS is more stricter, than normal WPCS. It is giving errors for some @ tags in the comments:

- `@author `tags are prohibited (WooCommerce.Commenting.CommentTags.AuthorTag)
- `@license` tags are prohibited (WooCommerce.Commenting.CommentTags.LicenseTag)
- `@access` tags are prohibited (WooCommerce.Commenting.CommentTags.AccessTag)

Please consider to change them to comply with WCCS also. This modification is required to validate the code for WooCommerce.com repository.

Example change in the persist-admin-notices-dismissal.php file:
`@author  Collins Agbonghama, Andy Fragen -> Author:  Collins Agbonghama, Andy Fragen`

Thank you if you consider this change in the code. That would make PAnD code valid for WC standards as well.

**Comment by afragen** [comment]
Why don't you simply ignore the vendor folder from your phpcs check?

**Comment by Surbma** [comment]
I can ignore, but WooCommerce.com doesn't ignore, so I have to deal with it. Everything that goes to WooCommerce.com Marketplace have to pass these coding standards.
