### ISSUE TITLE
Theoretical collision

### ISSUE THREAD

**Issue by afragen** [collizo4sky/persist-dismissible-admin-notices#7]
It's possible that 2 or more notices have the same name and collisions will result. I played with adding a hash but it wouldn't work as a static.

I'm still playing with it.

**Comment by w3guy** [comment]
Let me know your outcome. BTW i send u an invite as a collaborator. That should give you push access to the repo.

**Comment by afragen** [comment]
> Let me know your outcome. BTW i send u an invite as a collaborator. That should give you push access to the repo.

Thanks, for the time being I'll keep submitting PRs.

**Comment by afragen** [comment]
Upon further thought, I don't think this is likely to be an issue.

**Comment by w3guy** [comment]
😂
